import { AuthHandler } from "#auth/server";
import { CredentialsProvider } from "#auth/providers";

const options = {
    // random key generated by `openssl rand -hex 32`
    secret: "f2dfe5970050f2c2d2b804e1e7a7cc9397de6ffab0f29992e4184a4bb72df66b",
    providers: [
        CredentialsProvider({
            async authorize(credentials) {
                const res = await fetch(`${process.env.API_BASE_URL}/auth/sign-in`, {
                    method: "POST",
                    body: JSON.stringify({
                        identifier: credentials.username,
                        password: credentials.password,
                    }),
                });

                const user = await res.json();

                if (user) {
                    return user;
                }

                return null;
            },
        }),
    ],
};

export default AuthHandler(options);
